services:
  - type: web
    name: elab-website
    runtime: node
    buildCommand: npm install --legacy-peer-deps && npm run build
    startCommand: npm run preview
    envVars:
      - key: NODE_ENV
        value: production
    routes:
      - path: /
        matchType: prefix
    staticSite:
      publishDirectory: ./dist
